import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding...");
  await prisma.predictorRule.deleteMany();
  await prisma.review.deleteMany();
  await prisma.course.deleteMany();
  await prisma.college.deleteMany();

  const colleges = [
    { name: "IIT Bombay", slug: "iit-bombay", location: "Mumbai, Maharashtra", city: "Mumbai", state: "Maharashtra", fees: 250000, rating: 4.8, reviewCount: 312, placementPercent: 97, avgPackage: 2100000, highestPackage: 25000000, established: 1958, affiliation: "Autonomous", type: "Government", description: "Premier engineering institution known for cutting-edge research and exceptional placements.", courses: [{ name: "B.Tech Computer Science", duration: "4 years", fees: 250000, seats: 120, category: "Engineering" }, { name: "B.Tech Electrical", duration: "4 years", fees: 250000, seats: 80, category: "Engineering" }, { name: "MBA", duration: "2 years", fees: 400000, seats: 60, category: "Management" }], rules: [{ exam: "JEE_ADVANCED", rankMin: 1, rankMax: 100, branch: "Computer Science" }, { exam: "JEE_ADVANCED", rankMin: 100, rankMax: 300, branch: "Electrical Engineering" }] },
    { name: "IIT Delhi", slug: "iit-delhi", location: "New Delhi, Delhi", city: "New Delhi", state: "Delhi", fees: 245000, rating: 4.8, reviewCount: 289, placementPercent: 96, avgPackage: 2000000, highestPackage: 22000000, established: 1961, affiliation: "Autonomous", type: "Government", description: "World-class institution located in the nation's capital.", courses: [{ name: "B.Tech Computer Science", duration: "4 years", fees: 245000, seats: 100, category: "Engineering" }, { name: "B.Tech Electronics", duration: "4 years", fees: 245000, seats: 90, category: "Engineering" }], rules: [{ exam: "JEE_ADVANCED", rankMin: 1, rankMax: 150, branch: "Computer Science" }, { exam: "JEE_ADVANCED", rankMin: 150, rankMax: 400, branch: "Electronics" }] },
    { name: "IIT Madras", slug: "iit-madras", location: "Chennai, Tamil Nadu", city: "Chennai", state: "Tamil Nadu", fees: 240000, rating: 4.7, reviewCount: 265, placementPercent: 95, avgPackage: 1900000, highestPackage: 21000000, established: 1959, affiliation: "Autonomous", type: "Government", description: "Beacon of technical excellence in Chennai.", courses: [{ name: "B.Tech Computer Science", duration: "4 years", fees: 240000, seats: 110, category: "Engineering" }, { name: "B.Tech Aerospace", duration: "4 years", fees: 240000, seats: 60, category: "Engineering" }], rules: [{ exam: "JEE_ADVANCED", rankMin: 1, rankMax: 200, branch: "Computer Science" }, { exam: "JEE_ADVANCED", rankMin: 200, rankMax: 500, branch: "Aerospace" }] },
    { name: "IIT Kharagpur", slug: "iit-kharagpur", location: "Kharagpur, West Bengal", city: "Kharagpur", state: "West Bengal", fees: 235000, rating: 4.7, reviewCount: 342, placementPercent: 94, avgPackage: 1850000, highestPackage: 20000000, established: 1951, affiliation: "Autonomous", type: "Government", description: "India's oldest IIT with world-class programs.", courses: [{ name: "B.Tech Computer Science", duration: "4 years", fees: 235000, seats: 110, category: "Engineering" }, { name: "B.Tech Mining", duration: "4 years", fees: 235000, seats: 40, category: "Engineering" }], rules: [{ exam: "JEE_ADVANCED", rankMin: 50, rankMax: 250, branch: "Computer Science" }, { exam: "JEE_ADVANCED", rankMin: 250, rankMax: 600, branch: "Electrical Engineering" }] },
    { name: "BITS Pilani", slug: "bits-pilani", location: "Pilani, Rajasthan", city: "Pilani", state: "Rajasthan", fees: 550000, rating: 4.6, reviewCount: 421, placementPercent: 92, avgPackage: 1600000, highestPackage: 18000000, established: 1964, affiliation: "Deemed", type: "Deemed", description: "India's premier private technical university.", courses: [{ name: "B.E. Computer Science", duration: "4 years", fees: 550000, seats: 180, category: "Engineering" }, { name: "B.E. Electronics", duration: "4 years", fees: 550000, seats: 120, category: "Engineering" }], rules: [{ exam: "JEE_MAIN", rankMin: 1, rankMax: 2000, branch: "Computer Science" }, { exam: "JEE_MAIN", rankMin: 2000, rankMax: 5000, branch: "Electronics" }] },
    { name: "NIT Trichy", slug: "nit-trichy", location: "Tiruchirappalli, Tamil Nadu", city: "Tiruchirappalli", state: "Tamil Nadu", fees: 160000, rating: 4.4, reviewCount: 198, placementPercent: 89, avgPackage: 1200000, highestPackage: 12000000, established: 1964, affiliation: "Autonomous", type: "Government", description: "Top NIT with excellent engineering programs.", courses: [{ name: "B.Tech Computer Science", duration: "4 years", fees: 160000, seats: 90, category: "Engineering" }, { name: "B.Tech Mechanical", duration: "4 years", fees: 160000, seats: 80, category: "Engineering" }], rules: [{ exam: "JEE_MAIN", rankMin: 2000, rankMax: 8000, branch: "Computer Science" }, { exam: "JEE_MAIN", rankMin: 8000, rankMax: 15000, branch: "Electronics" }] },
    { name: "NIT Warangal", slug: "nit-warangal", location: "Warangal, Telangana", city: "Warangal", state: "Telangana", fees: 155000, rating: 4.3, reviewCount: 198, placementPercent: 88, avgPackage: 1150000, highestPackage: 11000000, established: 1959, affiliation: "Autonomous", type: "Government", description: "Premier government institution in Telangana.", courses: [{ name: "B.Tech CSE", duration: "4 years", fees: 155000, seats: 90, category: "Engineering" }, { name: "B.Tech Civil", duration: "4 years", fees: 155000, seats: 80, category: "Engineering" }], rules: [{ exam: "JEE_MAIN", rankMin: 3000, rankMax: 12000, branch: "Computer Science" }, { exam: "JEE_MAIN", rankMin: 12000, rankMax: 25000, branch: "Electronics" }] },
    { name: "IIM Ahmedabad", slug: "iim-ahmedabad", location: "Ahmedabad, Gujarat", city: "Ahmedabad", state: "Gujarat", fees: 2400000, rating: 4.9, reviewCount: 187, placementPercent: 100, avgPackage: 3500000, highestPackage: 80000000, established: 1961, affiliation: "Autonomous", type: "Government", description: "Asia's top business school with 100% placement.", courses: [{ name: "MBA (PGP)", duration: "2 years", fees: 2400000, seats: 400, category: "Management" }], rules: [{ exam: "CAT", rankMin: 1, rankMax: 50, branch: "MBA" }] },
    { name: "IIM Bangalore", slug: "iim-bangalore", location: "Bengaluru, Karnataka", city: "Bengaluru", state: "Karnataka", fees: 2300000, rating: 4.8, reviewCount: 201, placementPercent: 100, avgPackage: 3300000, highestPackage: 75000000, established: 1973, affiliation: "Autonomous", type: "Government", description: "One of India's most prestigious management institutions.", courses: [{ name: "MBA (PGP)", duration: "2 years", fees: 2300000, seats: 410, category: "Management" }], rules: [{ exam: "CAT", rankMin: 1, rankMax: 100, branch: "MBA" }] },
    { name: "AIIMS Delhi", slug: "aiims-delhi", location: "New Delhi, Delhi", city: "New Delhi", state: "Delhi", fees: 30000, rating: 4.9, reviewCount: 312, placementPercent: 100, avgPackage: 1800000, highestPackage: 8000000, established: 1956, affiliation: "Autonomous", type: "Government", description: "India's most prestigious medical institution.", courses: [{ name: "MBBS", duration: "5.5 years", fees: 30000, seats: 100, category: "Medical" }, { name: "MD/MS", duration: "3 years", fees: 20000, seats: 200, category: "Medical" }], rules: [{ exam: "NEET", rankMin: 1, rankMax: 100, branch: "MBBS" }] },
    { name: "VIT Vellore", slug: "vit-vellore", location: "Vellore, Tamil Nadu", city: "Vellore", state: "Tamil Nadu", fees: 420000, rating: 4.2, reviewCount: 534, placementPercent: 85, avgPackage: 900000, highestPackage: 8000000, established: 1984, affiliation: "Deemed", type: "Deemed", description: "Leading private university with strong industry connections.", courses: [{ name: "B.Tech CSE", duration: "4 years", fees: 420000, seats: 500, category: "Engineering" }, { name: "MBA", duration: "2 years", fees: 380000, seats: 120, category: "Management" }], rules: [{ exam: "JEE_MAIN", rankMin: 10000, rankMax: 50000, branch: "Computer Science" }] },
    { name: "DTU Delhi", slug: "dtu-delhi", location: "New Delhi, Delhi", city: "New Delhi", state: "Delhi", fees: 175000, rating: 4.3, reviewCount: 287, placementPercent: 88, avgPackage: 1100000, highestPackage: 10000000, established: 1941, affiliation: "State University", type: "Government", description: "One of the oldest and most reputed engineering colleges in India.", courses: [{ name: "B.Tech Computer Science", duration: "4 years", fees: 175000, seats: 180, category: "Engineering" }, { name: "B.Tech Software Engineering", duration: "4 years", fees: 175000, seats: 90, category: "Engineering" }], rules: [{ exam: "JEE_MAIN", rankMin: 3000, rankMax: 12000, branch: "Computer Science" }] },
    { name: "Jadavpur University", slug: "jadavpur-university", location: "Kolkata, West Bengal", city: "Kolkata", state: "West Bengal", fees: 45000, rating: 4.3, reviewCount: 221, placementPercent: 86, avgPackage: 1000000, highestPackage: 9000000, established: 1955, affiliation: "State University", type: "Government", description: "Prestigious state university renowned for engineering and science.", courses: [{ name: "B.E. Computer Science", duration: "4 years", fees: 45000, seats: 120, category: "Engineering" }], rules: [{ exam: "JEE_MAIN", rankMin: 5000, rankMax: 20000, branch: "Computer Science" }] },
    { name: "SRM University", slug: "srm-ist", location: "Chennai, Tamil Nadu", city: "Chennai", state: "Tamil Nadu", fees: 360000, rating: 3.9, reviewCount: 612, placementPercent: 80, avgPackage: 780000, highestPackage: 6000000, established: 1985, affiliation: "Deemed", type: "Deemed", description: "One of India's largest private universities.", courses: [{ name: "B.Tech CSE", duration: "4 years", fees: 360000, seats: 600, category: "Engineering" }, { name: "BBA", duration: "3 years", fees: 200000, seats: 200, category: "Management" }], rules: [{ exam: "JEE_MAIN", rankMin: 20000, rankMax: 80000, branch: "Computer Science" }] },
    { name: "Thapar Institute", slug: "thapar-institute", location: "Patiala, Punjab", city: "Patiala", state: "Punjab", fees: 310000, rating: 4.0, reviewCount: 264, placementPercent: 83, avgPackage: 880000, highestPackage: 7500000, established: 1956, affiliation: "Deemed", type: "Deemed", description: "Top-ranked private engineering institution in North India.", courses: [{ name: "B.E. Computer Engineering", duration: "4 years", fees: 310000, seats: 240, category: "Engineering" }], rules: [{ exam: "JEE_MAIN", rankMin: 8000, rankMax: 30000, branch: "Computer Engineering" }] },
  ];

  const reviews = [
    { author: "Rahul Sharma", rating: 5, content: "Exceptional faculty and world-class facilities. Best decision of my life.", batch: "2022" },
    { author: "Priya Nair", rating: 4, content: "Great placements and strong industry connections. Very rewarding experience.", batch: "2021" },
    { author: "Arjun Mehta", rating: 5, content: "Unmatched exposure and opportunities. The alumni network is incredible.", batch: "2023" },
  ];

  for (const college of colleges) {
    const { courses, rules, ...data } = college;
    const created = await prisma.college.create({
      data: {
        ...data,
        courses: { create: courses },
        reviews: { create: reviews },
        predictorRules: { create: rules },
      },
    });
    console.log(`✅ ${created.name}`);
  }
  console.log("🎉 Done!");
}

main().catch(console.error).finally(() => prisma.$disconnect());
